# **A/B Hypothesis Testing Analysis**

Risk Metrics:
* Claim Frequency: Proportion of policies with at least one claim
* Claim Severity: Average claim amount when a claim occurs

Profit Metric:
* Margin: TotalPremium - TotalClaims

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sys
import os

# Configure warnings (suppress non-critical warnings)
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

sys.path.append(os.path.abspath("../scripts"))

from hypothesis_testing import *

In [3]:
risk_analyzer = InsuranceRiskAnalyzer()

risk_analyzer.df.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,LegalType,Title,Bank,AccountType,MaritalStatus,Gender,...,CoverType,CoverGroup,Section,Product,TotalPremium,TotalClaims,has_claim,margin,loss_ratio,claim_frequency
0,145249,12827,2015-03-01,True,Close Corporation,Mr,First National Bank,Current account,Not specified,Not Specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,21.929825,0.0,False,21.929825,0.0,0
1,145249,12827,2015-05-01,True,Close Corporation,Mr,First National Bank,Current account,Not specified,Not Specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,21.929825,0.0,False,21.929825,0.0,0
2,145249,12827,2015-07-01,True,Close Corporation,Mr,First National Bank,Current account,Not specified,Not Specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,0.000000,0.0,False,0.000000,NaN,0
3,145255,12827,2015-05-01,True,Close Corporation,Mr,First National Bank,Current account,Not specified,Not Specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,512.848070,0.0,False,512.848070,0.0,0
4,145255,12827,2015-07-01,True,Close Corporation,Mr,First National Bank,Current account,Not specified,Not Specified,...,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,0.000000,0.0,False,0.000000,NaN,0

In [4]:
risk_analyzer.get_sample()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,LegalType,Title,Bank,AccountType,MaritalStatus,Gender,...,CoverType,CoverGroup,Section,Product,TotalPremium,TotalClaims,has_claim,margin,loss_ratio,claim_frequency
2143,138375,12071,2015-04-01,True,Individual,Miss,Capitec Bank,Current account,Not specified,Not Specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,21.929825,0.0,False,21.929825,0.0,0
2144,138375,12071,2015-06-01,True,Individual,Miss,Capitec Bank,Current account,Not specified,Not Specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,21.929825,0.0,False,21.929825,0.0,0
2289,138375,12071,2015-08-01,True,Individual,Miss,Capitec Bank,Current account,Not specified,Not Specified,...,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,21.929825,0.0,False,21.929825,0.0,0
2290,138374,12071,2015-02-01,True,Individual,Miss,Capitec Bank,Current account,Not specified,Not Specified,...,Income Protector,Income Protector,Optional Extended Covers,Mobility Commercial Cover: Monthly,74.561404,0.0,False,74.561404,0.0,0
2291,138369,12071,2015-03-01,True,Individual,Miss,Capitec Bank,Current account,Not specified,Not Specified,...,Emergency Charges,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,5.505789,0.0,False,5.505789,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996517,1672,195,2014-04-01,True,Individual,Mr,Standard Bank,Current account,Not specified,Not Specified,...,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,62.637193,0.0,False,62.637193,0.0,0
996518,1672,195,2014-06-01,True,Individual,Mr,Standard Bank,Current account,Not specified,Not Specified,...,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,62.637193,0.0,False,62.637193,0.0,0
996519,1672,195,2014-08-01,True,Individual,Mr,Standard Bank,Current account,Not specified,Not Specified,...,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,62.637193,0.0,False,62.637193,0.0,0
996520,1672,195,2014-10-01,True,Individual,Mr,Standard Bank,Current account,Not specified,Not Specified,...,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,62.637193,0.0,False,62.637193,0.0,0
996521,1672,195,2014-12-01,True,Individual,Mr,Standard Bank,Current account,Not specified,Not Specified,...,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,62.637193,0.0,False,62.637193,0.0,0